let levels = [
	['http://cse.nitk.ac.in'],
	[
		'sites',
		'content',
		'research',
		'programmes',
		'achievements',
		'contact-us',
		'research-consultancy',
		'facilities',
		'events',
		'courses',
		'people',
		'students',
		'staff',
		'placements',
		'courses-page',
		'course',
		'faculty',
		'researchscholars',
		'data-informatics-analytics-lab',
		'conferences',
		'information-security',
		'information-security-lab',
		'courses?qt-courses=2',
		'workshops',
		'people?qt-professorquicktab=1',
		'systems-networks-lab',
		'advanced-computing-lab-ist-year-pg',
		'facilities?qt-facilities=2',
		'achievements?qt-achievements=3',
		'achievements?qt-achievements=0',
		'events?qt-department_jobs=2',
		'computing-facility',
		'people?qt-professorquicktab=0',
		'distributed-cloud-computing-lab',
		'programmes?qt-programmes=2',
		'algorithms',
		'mtech-research-lab',
		'intel-e-commerce-multi-core-lab-mtech-cse-project-lab',
		'programmes?qt-programmes=1',
		'cse.nitk.ac.in',
		'programmes?qt-programmes=0',
		'network-engineering-lab',
		'distributed-and-cloud-computing',
		'facilities?qt-facilities=1',
		'professor',
		'achievements?qt-achievements=1',
		'speech-and-image-processing',
		'algorithms-lab',
		'events?qt-department_jobs=0',
		'data-informatics-and-analytics',
		'image-and-speech-processing-lab',
		'achievements?qt-achievements=2',
		'research-consultancy?qt-research_consultancy=0',
		'people?qt-professorquicktab=3',
		'people?qt-professorquicktab=2',
		'research-consultancy?qt-research_consultancy=1',
		'people?qt-professorquicktab=5',
		'microprocessor-lab',
		'internet-web-engineering-lab',
		'courses?qt-courses=1',
		'staff?page=1',
		'courses?qt-courses=0',
		'facilities?qt-facilities=0',
		'people?qt-professorquicktab=4',
		'computer-architecture',
		'events?qt-department_jobs=1',
		'computer-networks'
	],
	[
		'default',
		'mtech-stipend-details',
		'development',
		'temporary-teaching-vacancies',
		'faculty',
		'general',
		'doctoral',
		'ug',
		'workshops',
		'students',
		'lab',
		'pg',
		'consultancy',
		'conferences',
		'decision-support-system',
		'b-r-chandravarkar',
		'biometric-security',
		'theory-computation',
		'sharath-yaji',
		'international-symposium-cloud-and-service-computing-iscos-2012',
		'topics-speech-processing',
		'two-days-workshop-fundamentals-speech-processing',
		'cholars',
		'phd',
		'security-architecture-design-analysis',
		'upcoming',
		'national-award-best-ug-projects-2005',
		'ethical-hacking',
		'network-processors-and-network-design',
		'green-computing',
		'formal-methods-0',
		'advanced-cryptography',
		'3-days-workshop-unix-network-programming',
		'game-theory',
		'social-network-analysis',
		'simulation-and-modelling',
		'networks-lab',
		'two-days-workshop-android-application-development',
		'summer-school-next-generation-data-management',
		'completed',
		'mohit-p-tahiliani',
		'annappa',
		'chaithanya-lakshmi-m',
		'applied-algorithms',
		'mtechcse-2014-2016-batch',
		'secure-coding',
		'software-engineering-lab',
		'computer-programming-lab',
		'unix-network-programming',
		'performance-modelling-and-analysis',
		'best-paper-award-dr-p-santhi-thilagam',
		'network-optimization',
		'software-project-management',
		'protocol-engineering',
		'two-days-workshop-medical-image-computing',
		'alwyn-roshan-pais',
		'major-project-i',
		'mini-project-0',
		'introduction-computer-hardware',
		'manu-basavaraju',
		'vidya-myageri',
		'practical-trainingeducational-tour',
		'internet-security',
		'international-summer-school-leading-edge-software-engineering-iss-lese-2014',
		'rakshitha',
		'advanced-image-processing',
		'cryptanalysis',
		'object-oriented-systems',
		'btech',
		'short-term-training-program-recent-advances-and-research-directions-software-engineering',
		'soft-computing',
		'model-driven-computing',
		'one-day-workshop-school-children-%E2%80%9Cinformation-security%E2%80%9D-0',
		'multimedia-and-virtual-reality',
		'distributed-algorithms',
		'nitk-wings-4th-workshop-simulation-wired-and-wireless-networks-swn-2014',
		'service-oriented-computing',
		'network-management-0',
		'distributed-database-systems',
		'database-management-systems',
		'security-policies',
		'knowledge-based-computer-systems',
		'grid-computing',
		'btech-2011-2015-batch',
		'optimization-techniques-computing',
		'cloud-computing',
		'two-week-workshop-effective-teaching-learning-computer-programming',
		'computer-graphics-mini-project',
		'digital-image-processing',
		'distributed-object-computing',
		'shashidhar-g-koolagudi',
		'compiler-design',
		'research-oriented-advanced-programme-%E2%80%9C-information-security%E2%80%9D',
		'compiler-design-lab',
		'network-security',
		'information-security-audit',
		'information-security-0',
		'short-programme-opportunities-engineers-government-support-procedure-availing-credit',
		'international-conference-advanced-computing-networking-and-security-adcons-2011',
		'network-security-0',
		'c-aishwarya',
		'real-time-systems',
		'number-theory-and-cryptography',
		'software-architecture',
		'security-administration',
		'microprocessor-systems',
		'principles-programming-language',
		'mahendra-pratap-singh',
		'combinatorics',
		'workshop-network-simulator-3-ns-3',
		'object-technology',
		'p-santhi-thilagam',
		'algorithmic-graph-theory',
		'mtechcse-2013-2015-batch',
		'software-quality-assurance',
		'best-paper-award-dr-kchandrasekaran',
		'saumya-hegde',
		'vinnakota-saran-chaitanya',
		'number-theory-and-cryptography-0',
		'machine-intelligence',
		'major-project-%E2%80%93-ii',
		'software-testing-1',
		'data-warehousing-and-data-mining',
		'best-paper-award-dr-shashidhar-g-koolagudi',
		'anjali-jose',
		'multimedia-security',
		'distributed-computing',
		'researchscholars',
		'jeny-rajan',
		'distributed-operating-systems',
		'service-oriented-computing-0',
		'computer-organization-and-architecture',
		'computer-graphics-lab',
		'problem-solving-techniques-computers',
		'high-performance-computing',
		'operating-systems-lab-0',
		'3rd-international-conference-eco-friendly-computing-and-communication-systems-iceccs-2014',
		'fault-tolerant-computing',
		'erp-and-supply-chain-management',
		'number-theory-and-cryptography-1',
		'bioinformatics',
		'basavaraj-talawar',
		'computer-vision',
		'information-security-1',
		'management-information-systems',
		'mathematical-foundations-computer-science',
		'design-digital-systems',
		'information-retrieval',
		'mtech-htta',
		'mtech-research-students',
		'internet-technology-and-applications',
		'two-week-workshop-database-management-systems',
		'topics-computer-networks',
		'computational-complexity',
		'operating-systems-lab',
		'computer-networks-lab',
		'software-lab',
		'cyber-law-and-ethics',
		'compilers-lab',
		'cyber-forensics',
		'network-engineering-0',
		'mobile-and-wireless-network-security',
		'two-days-workshop-neural-networks-approach-speech-tasks',
		'design-digital-systems-lab',
		'one-day-workshop-school-children-%E2%80%9Cinformation-security%E2%80%9D',
		'distributed-computing-systems',
		'topics-data-management',
		'web-engineering-0',
		'vani-m',
		'web-application-security',
		'information-systems',
		'software-quality-assurance-0',
		'software-project-management-0',
		'ankit-gupta',
		'cloud-computing-0',
		'object-oriented-programming',
		'software-engineering-0',
		'database-systems',
		'advances-cryptography',
		'software-testing',
		'operating-systems-0',
		'database-management-systems-lab',
		'elementary-number-theory',
		'interconnection-networks',
		'vaishnavi-t',
		'operating-systems',
		'mobile-computing-0',
		'advanced-concepts-theoretical-computer-science',
		'marwa-mohiddin',
		'software-architecture-0',
		'modern-computation-algebra',
		'topics-algorithm-design',
		'cloud-security',
		'parallel-programming',
		'cryptographic-protocols',
		'database-security',
		'chandrasekaran-k',
		'mini-project',
		'data-structures-and-algorithms',
		'algorithms-and-complexity-0',
		'distributed-database-system',
		'two-week-workshop-effective-teaching-learning-computer-programming-0',
		'microprocessor-lab',
		'advanced-microsprocessors',
		'logic-computer-science',
		'advanced-data-structures',
		'power-aware-computing',
		'computer-graphics-and-multimedia',
		'systems-programming',
		'applied-cryptography',
		'advanced-topics-security',
		'data-communication',
		'advanced-computer-network',
		'advances-compiler-design',
		'wireless-networks',
		'advanced-data-structures-and-algorithms',
		'compiler-optimization',
		'systems-programming-0',
		'advanced-topics-networks-and-distributed-computing',
		'advanced-database-systems',
		'soft-computing-lab',
		'network-engineering',
		'computer-networks',
		'ankit-r-kurup',
		'data-structures-and-algorithms-lab',
		'two-week-workshop-cloud-computing-virtualization',
		'mobile-computing',
		'distributed-systems-security',
		'enterprise-security',
		'artificial-intelligence-and-expert-systems',
		'database-systems-lab',
		'information-retrieval-0',
		'one-day-workshop-information-security-awareness-school-teachers-dakshina-kannada-district',
		'distributed-algorithms-0',
		'm-venkatesan',
		'design-and-analysis-algorithms-0',
		'bites-best-phd-thesis-award-2009-dr-p-santhi-thilagam',
		'cryptography',
		'distributed-computing-lab',
		'security-threats-vulnerability',
		'wireless-networks-0',
		'ten-days-workshop-introduction-research-methodologies',
		'high-performance-computing-security',
		'btech-2012-2016-batch',
		'short-term-training-program-big-data-and-machine-learning-big-learn-2014',
		'information-security',
		'formal-methods',
		'mtechcse-is-2013-2015-batch',
		'design-and-analysis-algorithms',
		'software-engineering',
		'network-management',
		'high-preformance-computing',
		'database-engineering',
		'optimization-algorithms',
		'requirements-engineering',
		'btech-2013-2017-batch',
		'seminar',
		'computer-architecture-lab',
		'security-computer-system',
		'web-engineering',
		'data-warehousing-and-data-mining-0'
	],
	[
		'files',
		'siva-krishna-m-0',
		'%20Simulation%20and%20Modeling',
		'adcons2013',
		'sneha-kamble',
		'bheemappa-h-halavar',
		'pradyoth-hegde',
		'somesha-m',
		'swn-2012',
		'keerthi-srinivas-shetty',
		'shubham-dodia',
		'alkha-mohan',
		'spoorthy-v',
		'tojo-mathew',
		'Network%20Management',
		'linda-sara-mathew',
		'fathima-afroz',
		'pradeep-nazareth',
		'srinivas-routh',
		'saraswathi-koppad',
		'swn-2011',
		'computer-programming',
		'sujata-s-supanekar',
		'pawan-s-jogi',
		'Intelligent%20Information%20Retrieval',
		'softtest-2013',
		'niyas-s-0',
		'swathi-p',
		'd-venkata-naga-siva-kumar',
		'y-v-srinivasa-murthy',
		'siva-krishna-m',
		'ashwin-kumar',
		'wireless-networks-and-systems',
		'pradyodh-hegde',
		'christina-terese-joseph',
		'niyas-s',
		'yamanappa',
		'amit-praseed',
		'VLSI%20Systems-Design%20and%20Testing%3A%20Perspectives%20from%20Computer%20Engineering',
		'apurva-s-kittur',
		'Advanced%20Parallel%20Computation',
		'pravin-b-r',
		'tribid-debbarma',
		'pramod-hanmantrao-yelmewad',
		'srinivasa-k',
		'nikhil-chandrakant-mhala',
		'manjunatha',
		'Bioinformatics',
		'anoop-b-n',
		'Protocol%20Engineering',
		'Network%20Algorithms',
		'anil-kumar',
		'santhanam-raghavan',
		'anoop-b-n-0',
		'uma-priya-d',
		'ajnas-muhammad',
		'prabhu-prasad',
		'sachin-dattatraya-patil',
		'nagaratna-b-chittaragi',
		'Evolutionary%20Computing',
		'k-sivakumar-0',
		'raviraj-holla',
		'Software%20%26%20IT%20Systems%E2%80%93Architecture%2C%20Measurement%20and%20Testing',
		'Advanced%20Optimizing%20Compilers',
		'rashmi-adyapady-r',
		'alok-kumar',
		'marimuthu-c',
		'zubair-ahmad-lone',
		'manjunath-mulimani',
		'k-sivakumar',
		'swn-2013',
		'vishal-jitendrakumar-rathod',
		'kallinatha-h-d',
		'%20%20Software%20Reliability%20and%20Fault%20Tolerance',
		'Web%20Engineering',
		'Automatic%20Computing',
		'abhay-narayan',
		'akhila-p',
		'khyamling-parane'
	],
	['uploads', 'studentlist', 'faculty-cv']
];

let relation = [
	[
		[
			'sites',
			'content',
			'research',
			'programmes',
			'achievements',
			'contact-us',
			'research-consultancy',
			'facilities',
			'events',
			'courses',
			'people',
			'students',
			'staff',
			'placements',
			'courses-page',
			'course',
			'faculty',
			'researchscholars',
			'data-informatics-analytics-lab',
			'conferences',
			'information-security',
			'information-security-lab',
			'courses?qt-courses=2',
			'workshops',
			'people?qt-professorquicktab=1',
			'systems-networks-lab',
			'advanced-computing-lab-ist-year-pg',
			'facilities?qt-facilities=2',
			'achievements?qt-achievements=3',
			'achievements?qt-achievements=0',
			'events?qt-department_jobs=2',
			'computing-facility',
			'people?qt-professorquicktab=0',
			'distributed-cloud-computing-lab',
			'programmes?qt-programmes=2',
			'algorithms',
			'mtech-research-lab',
			'intel-e-commerce-multi-core-lab-mtech-cse-project-lab',
			'programmes?qt-programmes=1',
			'cse.nitk.ac.in',
			'programmes?qt-programmes=0',
			'network-engineering-lab',
			'distributed-and-cloud-computing',
			'facilities?qt-facilities=1',
			'professor',
			'achievements?qt-achievements=1',
			'speech-and-image-processing',
			'algorithms-lab',
			'events?qt-department_jobs=0',
			'data-informatics-and-analytics',
			'image-and-speech-processing-lab',
			'achievements?qt-achievements=2',
			'research-consultancy?qt-research_consultancy=0',
			'people?qt-professorquicktab=3',
			'people?qt-professorquicktab=2',
			'research-consultancy?qt-research_consultancy=1',
			'people?qt-professorquicktab=5',
			'microprocessor-lab',
			'internet-web-engineering-lab',
			'courses?qt-courses=1',
			'staff?page=1',
			'courses?qt-courses=0',
			'facilities?qt-facilities=0',
			'people?qt-professorquicktab=4',
			'computer-architecture',
			'events?qt-department_jobs=1',
			'computer-networks'
		],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[]
	],
	[
		['default'],
		[
			'mtech-stipend-details',
			'temporary-teaching-vacancies',
			'international-symposium-cloud-and-service-computing-iscos-2012',
			'two-days-workshop-fundamentals-speech-processing',
			'national-award-best-ug-projects-2005',
			'3-days-workshop-unix-network-programming',
			'two-days-workshop-android-application-development',
			'summer-school-next-generation-data-management',
			'best-paper-award-dr-p-santhi-thilagam',
			'two-days-workshop-medical-image-computing',
			'international-summer-school-leading-edge-software-engineering-iss-lese-2014',
			'short-term-training-program-recent-advances-and-research-directions-software-engineering',
			'one-day-workshop-school-children-%E2%80%9Cinformation-security%E2%80%9D-0',
			'nitk-wings-4th-workshop-simulation-wired-and-wireless-networks-swn-2014',
			'two-week-workshop-effective-teaching-learning-computer-programming',
			'research-oriented-advanced-programme-%E2%80%9C-information-security%E2%80%9D',
			'short-programme-opportunities-engineers-government-support-procedure-availing-credit',
			'international-conference-advanced-computing-networking-and-security-adcons-2011',
			'workshop-network-simulator-3-ns-3',
			'best-paper-award-dr-kchandrasekaran',
			'best-paper-award-dr-shashidhar-g-koolagudi',
			'3rd-international-conference-eco-friendly-computing-and-communication-systems-iceccs-2014',
			'two-week-workshop-database-management-systems',
			'two-days-workshop-neural-networks-approach-speech-tasks',
			'one-day-workshop-school-children-%E2%80%9Cinformation-security%E2%80%9D',
			'advances-cryptography',
			'two-week-workshop-effective-teaching-learning-computer-programming-0',
			'two-week-workshop-cloud-computing-virtualization',
			'one-day-workshop-information-security-awareness-school-teachers-dakshina-kannada-district',
			'bites-best-phd-thesis-award-2009-dr-p-santhi-thilagam',
			'cryptography',
			'ten-days-workshop-introduction-research-methodologies',
			'short-term-training-program-big-data-and-machine-learning-big-learn-2014'
		],
		['development', 'consultancy', 'cholars'],
		['doctoral', 'ug', 'pg'],
		['faculty', 'students'],
		[],
		[],
		['general', 'lab'],
		['workshops', 'conferences'],
		['ug', 'doctoral', 'pg', 'phd', 'btech'],
		[],
		[
			'mtechcse-2014-2016-batch',
			'btech-2011-2015-batch',
			'mtechcse-2013-2015-batch',
			'mtech-htta',
			'mtech-research-students',
			'btech-2012-2016-batch',
			'mtechcse-is-2013-2015-batch',
			'btech-2013-2017-batch'
		],
		[],
		[],
		[],
		[
			'decision-support-system',
			'biometric-security',
			'theory-computation',
			'topics-speech-processing',
			'security-architecture-design-analysis',
			'ethical-hacking',
			'network-processors-and-network-design',
			'green-computing',
			'formal-methods-0',
			'advanced-cryptography',
			'game-theory',
			'social-network-analysis',
			'simulation-and-modelling',
			'networks-lab',
			'applied-algorithms',
			'secure-coding',
			'software-engineering-lab',
			'computer-programming-lab',
			'unix-network-programming',
			'performance-modelling-and-analysis',
			'network-optimization',
			'software-project-management',
			'protocol-engineering',
			'major-project-i',
			'mini-project-0',
			'introduction-computer-hardware',
			'practical-trainingeducational-tour',
			'internet-security',
			'advanced-image-processing',
			'cryptanalysis',
			'object-oriented-systems',
			'soft-computing',
			'model-driven-computing',
			'multimedia-and-virtual-reality',
			'distributed-algorithms',
			'service-oriented-computing',
			'network-management-0',
			'distributed-database-systems',
			'database-management-systems',
			'security-policies',
			'knowledge-based-computer-systems',
			'grid-computing',
			'optimization-techniques-computing',
			'cloud-computing',
			'computer-graphics-mini-project',
			'digital-image-processing',
			'distributed-object-computing',
			'compiler-design',
			'compiler-design-lab',
			'network-security',
			'information-security-audit',
			'information-security-0',
			'network-security-0',
			'real-time-systems',
			'number-theory-and-cryptography',
			'software-architecture',
			'security-administration',
			'microprocessor-systems',
			'principles-programming-language',
			'combinatorics',
			'object-technology',
			'algorithmic-graph-theory',
			'software-quality-assurance',
			'number-theory-and-cryptography-0',
			'machine-intelligence',
			'major-project-%E2%80%93-ii',
			'software-testing-1',
			'data-warehousing-and-data-mining',
			'multimedia-security',
			'distributed-computing',
			'distributed-operating-systems',
			'service-oriented-computing-0',
			'computer-organization-and-architecture',
			'computer-graphics-lab',
			'problem-solving-techniques-computers',
			'high-performance-computing',
			'operating-systems-lab-0',
			'fault-tolerant-computing',
			'erp-and-supply-chain-management',
			'number-theory-and-cryptography-1',
			'bioinformatics',
			'computer-vision',
			'information-security-1',
			'management-information-systems',
			'mathematical-foundations-computer-science',
			'design-digital-systems',
			'information-retrieval',
			'internet-technology-and-applications',
			'topics-computer-networks',
			'computational-complexity',
			'operating-systems-lab',
			'computer-networks-lab',
			'software-lab',
			'cyber-law-and-ethics',
			'compilers-lab',
			'cyber-forensics',
			'network-engineering-0',
			'mobile-and-wireless-network-security',
			'design-digital-systems-lab',
			'distributed-computing-systems',
			'topics-data-management',
			'web-engineering-0',
			'web-application-security',
			'information-systems',
			'software-quality-assurance-0',
			'software-project-management-0',
			'cloud-computing-0',
			'object-oriented-programming',
			'software-engineering-0',
			'database-systems',
			'software-testing',
			'operating-systems-0',
			'database-management-systems-lab',
			'elementary-number-theory',
			'interconnection-networks',
			'operating-systems',
			'mobile-computing-0',
			'advanced-concepts-theoretical-computer-science',
			'software-architecture-0',
			'modern-computation-algebra',
			'topics-algorithm-design',
			'cloud-security',
			'parallel-programming',
			'cryptographic-protocols',
			'database-security',
			'mini-project',
			'data-structures-and-algorithms',
			'algorithms-and-complexity-0',
			'distributed-database-system',
			'microprocessor-lab',
			'advanced-microsprocessors',
			'logic-computer-science',
			'advanced-data-structures',
			'power-aware-computing',
			'computer-graphics-and-multimedia',
			'systems-programming',
			'applied-cryptography',
			'advanced-topics-security',
			'data-communication',
			'advanced-computer-network',
			'advances-compiler-design',
			'wireless-networks',
			'advanced-data-structures-and-algorithms',
			'compiler-optimization',
			'systems-programming-0',
			'advanced-topics-networks-and-distributed-computing',
			'advanced-database-systems',
			'soft-computing-lab',
			'network-engineering',
			'computer-networks',
			'data-structures-and-algorithms-lab',
			'mobile-computing',
			'distributed-systems-security',
			'enterprise-security',
			'artificial-intelligence-and-expert-systems',
			'database-systems-lab',
			'information-retrieval-0',
			'distributed-algorithms-0',
			'design-and-analysis-algorithms-0',
			'distributed-computing-lab',
			'security-threats-vulnerability',
			'wireless-networks-0',
			'high-performance-computing-security',
			'information-security',
			'formal-methods',
			'design-and-analysis-algorithms',
			'software-engineering',
			'network-management',
			'high-preformance-computing',
			'database-engineering',
			'optimization-algorithms',
			'requirements-engineering',
			'seminar',
			'computer-architecture-lab',
			'security-computer-system',
			'web-engineering',
			'data-warehousing-and-data-mining-0'
		],
		[
			'b-r-chandravarkar',
			'sharath-yaji',
			'mohit-p-tahiliani',
			'annappa',
			'chaithanya-lakshmi-m',
			'alwyn-roshan-pais',
			'manu-basavaraju',
			'vidya-myageri',
			'rakshitha',
			'shashidhar-g-koolagudi',
			'c-aishwarya',
			'mahendra-pratap-singh',
			'p-santhi-thilagam',
			'saumya-hegde',
			'vinnakota-saran-chaitanya',
			'anjali-jose',
			'jeny-rajan',
			'vani-m',
			'ankit-gupta',
			'vaishnavi-t',
			'marwa-mohiddin',
			'chandrasekaran-k',
			'ankit-r-kurup',
			'm-venkatesan'
		],
		[],
		[],
		['upcoming'],
		[],
		[],
		[],
		['completed'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		['researchscholars'],
		[],
		[],
		[],
		[],
		['basavaraj-talawar'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[]
	],
	[
		['files'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[
			'siva-krishna-m-0',
			'sneha-kamble',
			'bheemappa-h-halavar',
			'pradyoth-hegde',
			'somesha-m',
			'keerthi-srinivas-shetty',
			'shubham-dodia',
			'alkha-mohan',
			'spoorthy-v',
			'tojo-mathew',
			'linda-sara-mathew',
			'fathima-afroz',
			'pradeep-nazareth',
			'srinivas-routh',
			'saraswathi-koppad',
			'sujata-s-supanekar',
			'pawan-s-jogi',
			'niyas-s-0',
			'swathi-p',
			'd-venkata-naga-siva-kumar',
			'y-v-srinivasa-murthy',
			'siva-krishna-m',
			'ashwin-kumar',
			'pradyodh-hegde',
			'christina-terese-joseph',
			'niyas-s',
			'yamanappa',
			'amit-praseed',
			'apurva-s-kittur',
			'pravin-b-r',
			'tribid-debbarma',
			'pramod-hanmantrao-yelmewad',
			'srinivasa-k',
			'nikhil-chandrakant-mhala',
			'manjunatha',
			'anoop-b-n',
			'anil-kumar',
			'santhanam-raghavan',
			'anoop-b-n-0',
			'uma-priya-d',
			'ajnas-muhammad',
			'prabhu-prasad',
			'sachin-dattatraya-patil',
			'nagaratna-b-chittaragi',
			'k-sivakumar-0',
			'raviraj-holla',
			'rashmi-adyapady-r',
			'alok-kumar',
			'marimuthu-c',
			'zubair-ahmad-lone',
			'manjunath-mulimani',
			'k-sivakumar',
			'vishal-jitendrakumar-rathod',
			'kallinatha-h-d',
			'abhay-narayan',
			'akhila-p',
			'khyamling-parane'
		],
		[
			'%20Simulation%20and%20Modeling',
			'Network%20Management',
			'Intelligent%20Information%20Retrieval',
			'wireless-networks-and-systems',
			'VLSI%20Systems-Design%20and%20Testing%3A%20Perspectives%20from%20Computer%20Engineering',
			'Advanced%20Parallel%20Computation',
			'Bioinformatics',
			'Protocol%20Engineering',
			'Network%20Algorithms',
			'Evolutionary%20Computing',
			'Software%20%26%20IT%20Systems%E2%80%93Architecture%2C%20Measurement%20and%20Testing',
			'Advanced%20Optimizing%20Compilers',
			'%20%20Software%20Reliability%20and%20Fault%20Tolerance',
			'Web%20Engineering',
			'Automatic%20Computing'
		],
		[],
		['adcons2013'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		['swn-2012', 'swn-2011', 'softtest-2013', 'swn-2013'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		['computer-programming'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		['sujata-s-supanekar'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[]
	],
	[
		['uploads', 'studentlist', 'faculty-cv'],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[]
	],
	[
		[
			'cybersecuritysecond.pdf',
			'SUC%2719-Brochure.pdf',
			'IoTfinal-brochure_0.pdf',
			'btech2.2.pdf',
			'btech3.1.pdf',
			'mtech%201%28CS%29.pdf',
			'mtech2%28IS%29.pdf',
			'Temp_teaching_vacancies.pdf',
			'mtech%201%28IS%29.pdf',
			'btech2.1.pdf',
			'mtech2%28CS%29.pdf',
			'btech3.2.pdf',
			'M.Tech_.%20Award%20of%20schlarship.PDF'
		],
		[
			'6 S2.pdf',
			'4CSE-IS.pdf',
			'2CSE-IS.pdf',
			'8 S1.pdf',
			'2CSE.pdf',
			'6 S1.pdf',
			'4 S2.pdf',
			'8 S2.pdf',
			'4 S1.pdf',
			'4CSE.pdf'
		],
		[
			'Annappa-Apr-2018.docx',
			'MPS_CV_Web_NITK_2019.pdf',
			'resume_Jeny2019a.pdf'
		],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[],
		[]
	]
];

let treeData = {
	name: 'Top Level',
	children: [
		{
			name: 'Level 2: A',
			children: [{ name: 'Son of A' }, { name: 'Daughter of A' }]
		},
		{ name: 'Level 2: B' }
	]
};

function buildChildren(i, j) {
	for (; i < levels.length; i++) {
		let x = [];
		for (; j < levels[i].length; j++) {
			if (relation[i][j].length) {
				x.push({
					name: levels[i][j].replace(/\//g, '/'),
					children: buildChildren(i + 1, j)
				});
			} else
				x.push({name: levels[i][j]});
		}
		return x;
	}
}

// console.log(treeData);
// console.log('build children')
let reqData = buildChildren(0, 0);
treeData = reqData[0];
console.log('hey req data', reqData[0]);

var totalNodes = 0;
var maxLabelLength = 0;
// variables for drag/drop
var selectedNode = null;
var draggingNode = null;
// panning variables
var panSpeed = 200;
var panBoundary = 20; // Within 20px from edges will pan when dragging.
// Misc. variables
var i = 0;
var duration = 750;
var root;

// size of the diagram
var viewerWidth = $(document).width();
var viewerHeight = $(document).height();

var tree = d3.layout.tree().size([viewerHeight, viewerWidth]);

// define a d3 diagonal projection for use by the node paths later on.
var diagonal = d3.svg.diagonal().projection(function(d) {
	return [d.y, d.x];
});

// A recursive helper function for performing some setup by walking through all nodes

function visit(parent, visitFn, childrenFn) {
	if (!parent) return;

	visitFn(parent);

	var children = childrenFn(parent);
	if (children) {
		var count = children.length;
		for (var i = 0; i < count; i++) {
			visit(children[i], visitFn, childrenFn);
		}
	}
}

// Call visit function to establish maxLabelLength
visit(
	treeData,
	function(d) {
		totalNodes++;
		maxLabelLength = Math.max(d.name.length, maxLabelLength);
	},
	function(d) {
		return d.children && d.children.length > 0 ? d.children : null;
	}
);

// sort the tree according to the node names

function sortTree() {
	tree.sort(function(a, b) {
		return b.name.toLowerCase() < a.name.toLowerCase() ? 1 : -1;
	});
}
// Sort the tree initially incase the JSON isn't in a sorted order.
sortTree();

// TODO: Pan function, can be better implemented.

function pan(domNode, direction) {
	var speed = panSpeed;
	if (panTimer) {
		clearTimeout(panTimer);
		translateCoords = d3.transform(svgGroup.attr('transform'));
		if (direction == 'left' || direction == 'right') {
			translateX =
				direction == 'left'
					? translateCoords.translate[0] + speed
					: translateCoords.translate[0] - speed;
			translateY = translateCoords.translate[1];
		} else if (direction == 'up' || direction == 'down') {
			translateX = translateCoords.translate[0];
			translateY =
				direction == 'up'
					? translateCoords.translate[1] + speed
					: translateCoords.translate[1] - speed;
		}
		scaleX = translateCoords.scale[0];
		scaleY = translateCoords.scale[1];
		scale = zoomListener.scale();
		svgGroup
			.transition()
			.attr(
				'transform',
				'translate(' + translateX + ',' + translateY + ')scale(' + scale + ')'
			);
		d3.select(domNode)
			.select('g.node')
			.attr('transform', 'translate(' + translateX + ',' + translateY + ')');
		zoomListener.scale(zoomListener.scale());
		zoomListener.translate([translateX, translateY]);
		panTimer = setTimeout(function() {
			pan(domNode, speed, direction);
		}, 50);
	}
}

// Define the zoom function for the zoomable tree

function zoom() {
	svgGroup.attr(
		'transform',
		'translate(' + d3.event.translate + ')scale(' + d3.event.scale + ')'
	);
}

// define the zoomListener which calls the zoom function on the "zoom" event constrained within the scaleExtents
var zoomListener = d3.behavior
	.zoom()
	.scaleExtent([0.1, 3])
	.on('zoom', zoom);

function initiateDrag(d, domNode) {
	draggingNode = d;
	d3.select(domNode)
		.select('.ghostCircle')
		.attr('pointer-events', 'none');
	d3.selectAll('.ghostCircle').attr('class', 'ghostCircle show');
	d3.select(domNode).attr('class', 'node activeDrag');

	svgGroup.selectAll('g.node').sort(function(a, b) {
		// select the parent and sort the path's
		if (a.id != draggingNode.id) return 1;
		// a is not the hovered element, send "a" to the back
		else return -1; // a is the hovered element, bring "a" to the front
	});
	// if nodes has children, remove the links and nodes
	if (nodes.length > 1) {
		// remove link paths
		links = tree.links(nodes);
		nodePaths = svgGroup
			.selectAll('path.link')
			.data(links, function(d) {
				return d.target.id;
			})
			.remove();
		// remove child nodes
		nodesExit = svgGroup
			.selectAll('g.node')
			.data(nodes, function(d) {
				return d.id;
			})
			.filter(function(d, i) {
				if (d.id == draggingNode.id) {
					return false;
				}
				return true;
			})
			.remove();
	}

	// remove parent link
	parentLink = tree.links(tree.nodes(draggingNode.parent));
	svgGroup
		.selectAll('path.link')
		.filter(function(d, i) {
			if (d.target.id == draggingNode.id) {
				return true;
			}
			return false;
		})
		.remove();

	dragStarted = null;
}

// define the baseSvg, attaching a class for styling and the zoomListener
var baseSvg = d3
	.select('#tree-container')
	.append('svg')
	.attr('width', viewerWidth)
	.attr('height', viewerHeight)
	.attr('class', 'overlay')
	.call(zoomListener);

// Define the drag listeners for drag/drop behaviour of nodes.
dragListener = d3.behavior
	.drag()
	.on('dragstart', function(d) {
		if (d == root) {
			return;
		}
		dragStarted = true;
		nodes = tree.nodes(d);
		d3.event.sourceEvent.stopPropagation();
		// it's important that we suppress the mouseover event on the node being dragged. Otherwise it will absorb the mouseover event and the underlying node will not detect it d3.select(this).attr('pointer-events', 'none');
	})
	.on('drag', function(d) {
		if (d == root) {
			return;
		}
		if (dragStarted) {
			domNode = this;
			initiateDrag(d, domNode);
		}

		// get coords of mouseEvent relative to svg container to allow for panning
		relCoords = d3.mouse($('svg').get(0));
		if (relCoords[0] < panBoundary) {
			panTimer = true;
			pan(this, 'left');
		} else if (relCoords[0] > $('svg').width() - panBoundary) {
			panTimer = true;
			pan(this, 'right');
		} else if (relCoords[1] < panBoundary) {
			panTimer = true;
			pan(this, 'up');
		} else if (relCoords[1] > $('svg').height() - panBoundary) {
			panTimer = true;
			pan(this, 'down');
		} else {
			try {
				clearTimeout(panTimer);
			} catch (e) {}
		}

		d.x0 += d3.event.dy;
		d.y0 += d3.event.dx;
		var node = d3.select(this);
		node.attr('transform', 'translate(' + d.y0 + ',' + d.x0 + ')');
		updateTempConnector();
	})
	.on('dragend', function(d) {
		if (d == root) {
			return;
		}
		domNode = this;
		if (selectedNode) {
			// now remove the element from the parent, and insert it into the new elements children
			var index = draggingNode.parent.children.indexOf(draggingNode);
			if (index > -1) {
				draggingNode.parent.children.splice(index, 1);
			}
			if (
				typeof selectedNode.children !== 'undefined' ||
				typeof selectedNode._children !== 'undefined'
			) {
				if (typeof selectedNode.children !== 'undefined') {
					selectedNode.children.push(draggingNode);
				} else {
					selectedNode._children.push(draggingNode);
				}
			} else {
				selectedNode.children = [];
				selectedNode.children.push(draggingNode);
			}
			// Make sure that the node being added to is expanded so user can see added node is correctly moved
			expand(selectedNode);
			sortTree();
			endDrag();
		} else {
			endDrag();
		}
	});

function endDrag() {
	selectedNode = null;
	d3.selectAll('.ghostCircle').attr('class', 'ghostCircle');
	d3.select(domNode).attr('class', 'node');
	// now restore the mouseover event or we won't be able to drag a 2nd time
	d3.select(domNode)
		.select('.ghostCircle')
		.attr('pointer-events', '');
	updateTempConnector();
	if (draggingNode !== null) {
		update(root);
		centerNode(draggingNode);
		draggingNode = null;
	}
}

// Helper functions for collapsing and expanding nodes.

function collapse(d) {
	if (d.children) {
		d._children = d.children;
		d._children.forEach(collapse);
		d.children = null;
	}
}

function expand(d) {
	if (d._children) {
		d.children = d._children;
		d.children.forEach(expand);
		d._children = null;
	}
}

var overCircle = function(d) {
	selectedNode = d;
	updateTempConnector();
};
var outCircle = function(d) {
	selectedNode = null;
	updateTempConnector();
};

// Function to update the temporary connector indicating dragging affiliation
var updateTempConnector = function() {
	var data = [];
	if (draggingNode !== null && selectedNode !== null) {
		// have to flip the source coordinates since we did this for the existing connectors on the original tree
		data = [
			{
				source: {
					x: selectedNode.y0,
					y: selectedNode.x0
				},
				target: {
					x: draggingNode.y0,
					y: draggingNode.x0
				}
			}
		];
	}
	var link = svgGroup.selectAll('.templink').data(data);

	link
		.enter()
		.append('path')
		.attr('class', 'templink')
		.attr('d', d3.svg.diagonal())
		.attr('pointer-events', 'none');

	link.attr('d', d3.svg.diagonal());

	link.exit().remove();
};

// Function to center node when clicked/dropped so node doesn't get lost when collapsing/moving with large amount of children.

function centerNode(source) {
	scale = zoomListener.scale();
	x = -source.y0;
	y = -source.x0;
	x = x * scale + viewerWidth / 2;
	y = y * scale + viewerHeight / 2;
	d3.select('g')
		.transition()
		.duration(duration)
		.attr('transform', 'translate(' + x + ',' + y + ')scale(' + scale + ')');
	zoomListener.scale(scale);
	zoomListener.translate([x, y]);
}

// Toggle children function

function toggleChildren(d) {
	if (d.children) {
		d._children = d.children;
		d.children = null;
	} else if (d._children) {
		d.children = d._children;
		d._children = null;
	}
	return d;
}

// Toggle children on click.

function click(d) {
	if (d3.event.defaultPrevented) return; // click suppressed
	d = toggleChildren(d);
	update(d);
	centerNode(d);
}

function update(source) {
	// Compute the new height, function counts total children of root node and sets tree height accordingly.
	// This prevents the layout looking squashed when new nodes are made visible or looking sparse when nodes are removed
	// This makes the layout more consistent.
	var levelWidth = [1];
	var childCount = function(level, n) {
		if (n.children && n.children.length > 0) {
			if (levelWidth.length <= level + 1) levelWidth.push(0);

			levelWidth[level + 1] += n.children.length;
			n.children.forEach(function(d) {
				childCount(level + 1, d);
			});
		}
	};
	childCount(0, root);
	var newHeight = d3.max(levelWidth) * 25; // 25 pixels per line
	tree = tree.size([newHeight, viewerWidth]);

	// Compute the new tree layout.
	var nodes = tree.nodes(root).reverse(),
		links = tree.links(nodes);

	// Set widths between levels based on maxLabelLength.
	nodes.forEach(function(d) {
		d.y = d.depth * (maxLabelLength * 10); //maxLabelLength * 10px
		// alternatively to keep a fixed scale one can set a fixed depth per level
		// Normalize for fixed-depth by commenting out below line
		// d.y = (d.depth * 500); //500px per level.
	});

	// Update the nodes…
	node = svgGroup.selectAll('g.node').data(nodes, function(d) {
		return d.id || (d.id = ++i);
	});

	// Enter any new nodes at the parent's previous position.
	var nodeEnter = node
		.enter()
		.append('g')
		.call(dragListener)
		.attr('class', 'node')
		.attr('transform', function(d) {
			return 'translate(' + source.y0 + ',' + source.x0 + ')';
		})
		.on('click', click);

	nodeEnter
		.append('circle')
		.attr('class', 'nodeCircle')
		.attr('r', 0)
		.style('fill', function(d) {
			return d._children ? 'lightsteelblue' : '#fff';
		});

	nodeEnter
		.append('text')
		.attr('x', function(d) {
			return d.children || d._children ? -10 : 10;
		})
		.attr('dy', '.35em')
		.attr('class', 'nodeText')
		.attr('text-anchor', function(d) {
			return d.children || d._children ? 'end' : 'start';
		})
		.text(function(d) {
			return d.name;
		})
		.style('fill-opacity', 0);

	// phantom node to give us mouseover in a radius around it
	nodeEnter
		.append('circle')
		.attr('class', 'ghostCircle')
		.attr('r', 30)
		.attr('opacity', 0.2) // change this to zero to hide the target area
		.style('fill', 'red')
		.attr('pointer-events', 'mouseover')
		.on('mouseover', function(node) {
			overCircle(node);
		})
		.on('mouseout', function(node) {
			outCircle(node);
		});

	// Update the text to reflect whether node has children or not.
	node
		.select('text')
		.attr('x', function(d) {
			return d.children || d._children ? -10 : 10;
		})
		.attr('text-anchor', function(d) {
			return d.children || d._children ? 'end' : 'start';
		})
		.text(function(d) {
			return d.name;
		});

	// Change the circle fill depending on whether it has children and is collapsed
	node
		.select('circle.nodeCircle')
		.attr('r', 4.5)
		.style('fill', function(d) {
			return d._children ? 'lightsteelblue' : '#fff';
		});

	// Transition nodes to their new position.
	var nodeUpdate = node
		.transition()
		.duration(duration)
		.attr('transform', function(d) {
			return 'translate(' + d.y + ',' + d.x + ')';
		});

	// Fade the text in
	nodeUpdate.select('text').style('fill-opacity', 1);

	// Transition exiting nodes to the parent's new position.
	var nodeExit = node
		.exit()
		.transition()
		.duration(duration)
		.attr('transform', function(d) {
			return 'translate(' + source.y + ',' + source.x + ')';
		})
		.remove();

	nodeExit.select('circle').attr('r', 0);

	nodeExit.select('text').style('fill-opacity', 0);

	// Update the links…
	var link = svgGroup.selectAll('path.link').data(links, function(d) {
		return d.target.id;
	});

	// Enter any new links at the parent's previous position.
	link
		.enter()
		.insert('path', 'g')
		.attr('class', 'link')
		.attr('d', function(d) {
			var o = {
				x: source.x0,
				y: source.y0
			};
			return diagonal({
				source: o,
				target: o
			});
		});

	// Transition links to their new position.
	link
		.transition()
		.duration(duration)
		.attr('d', diagonal);

	// Transition exiting nodes to the parent's new position.
	link
		.exit()
		.transition()
		.duration(duration)
		.attr('d', function(d) {
			var o = {
				x: source.x,
				y: source.y
			};
			return diagonal({
				source: o,
				target: o
			});
		})
		.remove();

	// Stash the old positions for transition.
	nodes.forEach(function(d) {
		d.x0 = d.x;
		d.y0 = d.y;
	});
}

// Append a group which holds all nodes and which the zoom Listener can act upon.
var svgGroup = baseSvg.append('g');

// Define the root
root = treeData;
root.x0 = viewerHeight / 2;
root.y0 = 0;
root.children.forEach(collapse);

// Layout the tree initially and center on the root node.
update(root);
centerNode(root);
